######################################################################
# Automatically generated by qmake (3.0) Mon Oct 15 11:49:18 2018
######################################################################

TEMPLATE = app
TARGET = exam
INCLUDEPATH += .

QT += widgets

# Input
SOURCES += scroller.cpp
